2020-04-30 00:17:12.241 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:17:54.409 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:20:00.048 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:20:48.693 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:25:28.681 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:27:26.574 +03:00 [Error] verify error
DwapiCentral.SharedKernel.Exceptions.SubscriberNotFoundException: Subscriber DWAPI not found
   at DwapiCentral.Cbs.Core.CommandHandler.VerifySubscriberHandler.Handle(VerifySubscriber request, CancellationToken cancellationToken) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/CommandHandler/VerifySubscriberHandler.cs:line 34
   at DwapiCentral.Controllers.MgsController.Verify(VerifySubscriber subscriber) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Controllers/MgsController.cs:line 42
2020-04-30 00:37:24.666 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:d6ce3ddf-6cc2-49fb-9926-955ce0c17d50
Error Number:2714,State:6,Class:16
2020-04-30 00:41:56.426 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:79d91d69-eae2-4eda-bfcc-a0d33c19bf9e
Error Number:2714,State:6,Class:16
2020-04-30 00:52:30.636 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:2ab30707-0134-4c98-94f1-9b0b1116e2db
Error Number:2714,State:6,Class:16
2020-04-30 00:54:15.062 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:63471d72-8969-4cd3-ad8c-520d2b3dc82b
Error Number:2714,State:6,Class:16
2020-04-30 01:01:02.925 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:01:02.928 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:01:02.928 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:01:02.928 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:01:02.929 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:01:02.929 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.757 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.758 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.758 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.765 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.765 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
2020-04-30 01:06:21.765 +03:00 [Error] Facility Id missing 10009
DwapiCentral.SharedKernel.Exceptions.FacilityNotFoundException: Facility not found with MFL Code 10009
   at DwapiCentral.Cbs.Core.Service.MgsService.GetFacilityId(Int32 siteCode) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 68
   at DwapiCentral.Cbs.Core.Service.MgsService.Process(IEnumerable`1 metricMigrationExtracts) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral.Cbs.Core/Service/MgsService.cs:line 37
r(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:e3629e41-ff01-469e-a013-d6a669855e2f
Error Number:2714,State:6,Class:16
2020-04-30 00:56:48.609 +03:00 [Fatal] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-04-30 00:56:48.956 +03:00 [Fatal] Host terminated unexpectedly
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at DwapiCentral.Program.Main(String[] args) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Program.cs:line 30
2020-04-30 00:58:50.180 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:dc4c59a7-c90a-4d52-ad76-8d63253a8681
Error Number:2714,State:6,Class:16
2020-04-30 00:58:51.991 +03:00 [Fatal] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-04-30 00:58:52.367 +03:00 [Fatal] Host terminated unexpectedly
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at DwapiCentral.Program.Main(String[] args) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Program.cs:line 30
2020-04-30 01:03:57.144 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:a4ca2a93-68bf-4cdc-a059-9390b2da4629
Error Number:2714,State:6,Class:16
2020-04-30 01:03:59.137 +03:00 [Fatal] Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
2020-04-30 01:03:59.498 +03:00 [Fatal] Host terminated unexpectedly
System.IO.IOException: Failed to bind to address http://[::]:6767: address already in use. ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use ---> System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransport.BindAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.<>c__DisplayClass22_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at DwapiCentral.Program.Main(String[] args) in /Users/koskedk/Projects/hmis/HTSCentral/DwapiCentral/Program.cs:line 30
2020-04-30 01:16:49.128 +03:00 [Error] Failed executing DbCommand ("4"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:2de6a82f-53cb-4fc1-b1d6-b2941a4eef4e
Error Number:2714,State:6,Class:16
2020-04-30 01:19:12.843 +03:00 [Error] Failed executing DbCommand ("3"ms) [Parameters=[""], CommandType='Text', CommandTimeout='30']"
""CREATE TABLE [Dockets] (
    [Id] nvarchar(450) NOT NULL,
    [Name] nvarchar(max) NULL,
    [Instance] nvarchar(max) NULL,
    CONSTRAINT [PK_Dockets] PRIMARY KEY ([Id])
);"
System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'Dockets' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ClientConnectionId:981f76fa-81fc-458b-8b22-55c32a48c753
Error Number:2714,State:6,Class:16
